# Experiment no 05

Name - Kaushl Powar    
Roll no 19

In [1]:
 #1) Write a R program to create a blank matrix. 
 mat = matrix(, nrow = 1, ncol = 1)
 print(mat)

     [,1]
[1,]   NA


In [27]:
#2. Write a R program to create a matrix taking a given vector of numbers as input. 
#Display the matrix.  
Matx = matrix(c(1:12), nrow = 3, byrow = TRUE)
print("Original Matrix is:")
print(Matx)

[1] "Original Matrix is:"
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12


In [29]:
#3. Write a R program to create a matrix taking a given vector of numbers as input and define the column and row names.
# Display the matrix
rownames(Matx) <- c("Row 1", "Row 2","Row 3")
colnames(Matx) <- c("Column 1", "Column 2", "Column 3", "Column 4")

In [30]:
Matx

A matrix: 3 × 4 of type int 
 
 Column 1 Column 2 Column 3 Column 4 
 
 
 Row 1 1 2 3 4 
 Row 2 5 6 7 8 
 Row 3 9 10 11 12

In [47]:
#4. Write a R program to access the element at 3rd column and 2nd row, only the 3rd row and only the 4th column of a given matrix. 
Matx[3, 2] 
Matx[3,]
Matx[,4]

10

Column 1 9 Column 2 10 Column 3 11 Column 4 12

Row 1 4 Row 2 8 Row 3 12

In [3]:
#5. Write a R program to create two 2x3 matrix and add, subtract, multiply and divide the matrixes. 
Mat = matrix(c(1:6), nrow = 2, byrow = TRUE)
Mat2 = matrix(c(4:9), nrow = 2, byrow = TRUE)

In [4]:
#Addition
Mat + Mat2

A matrix: 2 × 3 of type int 
 
 5 7 9 
 11 13 15

In [5]:
#Subtraction
Mat2-Mat

A matrix: 2 × 3 of type int 
 
 3 3 3 
 3 3 3

In [6]:
#Multiplication
Mat * Mat2

A matrix: 2 × 3 of type int 
 
 4 10 18 
 28 40 54

In [7]:
#Division
Mat2/Mat

A matrix: 2 × 3 of type dbl 
 
 4.00 2.5 2.0 
 1.75 1.6 1.5

In [8]:
#6.Write a R program to create a matrix from a list of given vectors. 
list1 = list()
for (i in 1:5) list1[[i]] <- c(i, 1:4)
print("List of vectors:")
print(list1)
result = do.call(rbind, list1)
print("New Matrix:")
print(result)

[1] "List of vectors:"
[[1]]
[1] 1 1 2 3 4

[[2]]
[1] 2 1 2 3 4

[[3]]
[1] 3 1 2 3 4

[[4]]
[1] 4 1 2 3 4

[[5]]
[1] 5 1 2 3 4

[1] "New Matrix:"
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    1    2    3    4
[2,]    2    1    2    3    4
[3,]    3    1    2    3    4
[4,]    4    1    2    3    4
[5,]    5    1    2    3    4


In [9]:
row_names = c("row1", "row2", "row3", "row4")
col_names = c("col1", "col2", "col3", "col4")
M = matrix(c(1:16), nrow = 4, byrow = TRUE, dimnames = list(row_names, col_names))
print("Original Matrix:")
print(M)
result = M[M[,3] > 7,]
print("New submatrix:")
print(result)

[1] "Original Matrix:"
     col1 col2 col3 col4
row1    1    2    3    4
row2    5    6    7    8
row3    9   10   11   12
row4   13   14   15   16
[1] "New submatrix:"
     col1 col2 col3 col4
row3    9   10   11   12
row4   13   14   15   16


In [10]:
#8. Write a R program to convert a matrix to a 1 dimensional array. 
m=matrix(1:12,3,4)
print("Original matrix:")
print(m)
a = as.vector(m)
print("1 dimensional array:")
print(a)

[1] "Original matrix:"
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
[1] "1 dimensional array:"
 [1]  1  2  3  4  5  6  7  8  9 10 11 12


In [11]:
#9. Write a R program to create a correlation matrix from a dataframe of same data type. 
d = data.frame(x1=rnorm(5),
               x2=rnorm(5),
               x3=rnorm(5))
print("Original dataframe:")   
print(d)
result = cor(d) 
print("Correlation matrix:")
print(result)

[1] "Original dataframe:"
           x1         x2         x3
1  0.03655076 -0.6472708  0.0777935
2 -0.10080700  0.4675166 -1.2502298
3 -0.41248416 -0.4281775 -0.6421040
4 -1.74419063  1.6729692  1.1823229
5 -0.38417633 -1.3872886  0.6045416
[1] "Correlation matrix:"
           x1         x2         x3
x1  1.0000000 -0.7336682 -0.6973526
x2 -0.7336682  1.0000000  0.1709821
x3 -0.6973526  0.1709821  1.0000000


In [12]:
#10. Write a R program to convert a given matrix to a list of column-vectors. 
x = matrix(1:12, ncol=3)
print("Original matrix:")
print(x)
print("list from the said matrix:")
l =  split(x, rep(1:ncol(x), each = nrow(x)))
print(l)

[1] "Original matrix:"
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
[1] "list from the said matrix:"
$`1`
[1] 1 2 3 4

$`2`
[1] 5 6 7 8

$`3`
[1]  9 10 11 12



In [13]:
#11. Write a R program to find row and column index of maximum and minimum value in a given matrix. 
m = matrix(c(1:16), nrow = 4, byrow = TRUE)
print("Original Matrix:")
print(m)
result = which(m == max(m), arr.ind=TRUE)
print("Row and column of maximum value of the said matrix:")
print(result)
result = which(m == min(m), arr.ind=TRUE)
print("Row and column of minimum value of the said matrix:")
print(result)

[1] "Original Matrix:"
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
[4,]   13   14   15   16
[1] "Row and column of maximum value of the said matrix:"
     row col
[1,]   4   4
[1] "Row and column of minimum value of the said matrix:"
     row col
[1,]   1   1


In [14]:
#12. Write a R program to rotate a given matrix 90 degree clockwise rotation. 
x =  matrix(1:9, 3)
print("Original matrix:")
print(x)
rotate = t(apply(x, 2, rev))
print("Rotate the said matrix 90 degree clockwise:")
print(rotate)

[1] "Original matrix:"
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] "Rotate the said matrix 90 degree clockwise:"
     [,1] [,2] [,3]
[1,]    3    2    1
[2,]    6    5    4
[3,]    9    8    7


In [15]:
#13.Write a R program to concatenate two given matrices of same column but different rows. 
x = matrix(1:12, ncol=3)
y = matrix(13:24, ncol=3)
print("Matrix-1")
print(x)
print("Matrix-2")
print(y)
result = dim(rbind(x,y))
print("After concatenating two given matrices:")
print(result)

[1] "Matrix-1"
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
[1] "Matrix-2"
     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24
[1] "After concatenating two given matrices:"
[1] 8 3


# **Array**

In [16]:
#1.Write a R program to convert a given matrix to a 1 dimensional array.  
m=matrix(1:12,3,4)
print("Original matrix:")
print(m)
a = as.vector(m)
print("1 dimensional array:")
print(a)

[1] "Original matrix:"
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
[1] "1 dimensional array:"
 [1]  1  2  3  4  5  6  7  8  9 10 11 12


In [17]:
#2. Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors. 
print("Two vectors of different lengths:")
v1 =  c(1,3,4,5)
v2 =  c(10,11,12,13,14,15)
print(v1)
print(v2)
result = array(c(v1,v2),dim = c(3,3,2))
print("New array:")
print(result)
print("The second row of the second matrix of the array:")
print(result[2,,2])
print("The element in the 3rd row and 3rd column of the 1st matrix:")
print(result[3,3,1])

[1] "Two vectors of different lengths:"
[1] 1 3 4 5
[1] 10 11 12 13 14 15
[1] "New array:"
, , 1

     [,1] [,2] [,3]
[1,]    1    5   12
[2,]    3   10   13
[3,]    4   11   14

, , 2

     [,1] [,2] [,3]
[1,]   15    4   11
[2,]    1    5   12
[3,]    3   10   13

[1] "The second row of the second matrix of the array:"
[1]  1  5 12
[1] "The element in the 3rd row and 3rd column of the 1st matrix:"
[1] 14


In [2]:
#3.Write a R program to create an 3 dimensional array of 24 elements using the dim() function.
v =  sample(1:5,24,replace = TRUE)
dim(v) = c(3,2,4)
print("3-dimension array:")
print(v)

[1] "3-dimension array:"
, , 1

     [,1] [,2]
[1,]    1    2
[2,]    2    4
[3,]    4    5

, , 2

     [,1] [,2]
[1,]    5    2
[2,]    2    5
[3,]    1    5

, , 3

     [,1] [,2]
[1,]    5    1
[2,]    4    2
[3,]    1    2

, , 4

     [,1] [,2]
[1,]    2    1
[2,]    3    3
[3,]    4    4



In [4]:
#4.Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors. Print the second row of the second matrix of the array and the element in the 3rd row and 3rd column of the 1st matrix.  
print("Two vectors of different lengths:")
v1 =  c(1,3,4,5)
v2 =  c(10,11,12,13,14,15)
print(v1)
print(v2)
result = array(c(v1,v2),dim = c(3,3,2))
print("New array:")
print(result)
print("The second row of the second matrix of the array:")
print(result[2,,2])
print("The element in the 3rd row and 3rd column of the 1st matrix:")
print(result[3,3,1])

[1] "Two vectors of different lengths:"
[1] 1 3 4 5
[1] 10 11 12 13 14 15
[1] "New array:"
, , 1

     [,1] [,2] [,3]
[1,]    1    5   12
[2,]    3   10   13
[3,]    4   11   14

, , 2

     [,1] [,2] [,3]
[1,]   15    4   11
[2,]    1    5   12
[3,]    3   10   13

[1] "The second row of the second matrix of the array:"
[1]  1  5 12
[1] "The element in the 3rd row and 3rd column of the 1st matrix:"
[1] 14


In [5]:
#5.Write a R program to combine three arrays so that the first row of the first array is followed by the first row of the second array and then first row of the third array.  
num1 = rbind(rep("A",3), rep("B",3), rep("C",3))
print("num1")
print(num1)
num2 = rbind(rep("P",3), rep("Q",3), rep("R",3))
print("num2")
print(num2)
num3 = rbind(rep("X",3), rep("Y",3), rep("Z",3))
print("num3")
print(num3)
a = matrix(t(cbind(num1,num2,num3)),ncol=3, byrow=T)
print("Combine three arrays, taking one row from each one by one:")
print(a)

[1] "num1"
     [,1] [,2] [,3]
[1,] "A"  "A"  "A" 
[2,] "B"  "B"  "B" 
[3,] "C"  "C"  "C" 
[1] "num2"
     [,1] [,2] [,3]
[1,] "P"  "P"  "P" 
[2,] "Q"  "Q"  "Q" 
[3,] "R"  "R"  "R" 
[1] "num3"
     [,1] [,2] [,3]
[1,] "X"  "X"  "X" 
[2,] "Y"  "Y"  "Y" 
[3,] "Z"  "Z"  "Z" 
[1] "Combine three arrays, taking one row from each one by one:"
      [,1] [,2] [,3]
 [1,] "A"  "A"  "A" 
 [2,] "P"  "P"  "P" 
 [3,] "X"  "X"  "X" 
 [4,] "B"  "B"  "B" 
 [5,] "Q"  "Q"  "Q" 
 [6,] "Y"  "Y"  "Y" 
 [7,] "C"  "C"  "C" 
 [8,] "R"  "R"  "R" 
 [9,] "Z"  "Z"  "Z" 


In [6]:
#6.Write a R program to create an array using four given columns, three given rows, and two given tables and display the content of the array. 
array1 =  array(1:30, dim=c(3,5,2))
print(array1)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    7   10   13
[2,]    2    5    8   11   14
[3,]    3    6    9   12   15

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   16   19   22   25   28
[2,]   17   20   23   26   29
[3,]   18   21   24   27   30



In [7]:
#7. Write a R program to create a two-dimensional 5x3 array of sequence of even integers greater than 50. 
a <- array(seq(from = 50, length.out = 15, by = 2), c(5, 3))
print("Content of the array:")
print("5×3 array of sequence of even integers greater than 50:")
print(a)

[1] "Content of the array:"
[1] "5×3 array of sequence of even integers greater than 50:"
     [,1] [,2] [,3]
[1,]   50   60   70
[2,]   52   62   72
[3,]   54   64   74
[4,]   56   66   76
[5,]   58   68   78
